### ISSUE TITLE
Clarify items in examples TODO

### ISSUE THREAD

**Issue by hategan** [ExaWorks/job-api-spec#48]
This was an in-line TODO item.

There's a PR that addresses some of the examples mentioned in that TODO item, but not all. The ones not addressed are not entirely clear. The reasons are listed below:

- [ ] do the same but use the ListException from the submit call to do
  the same

"the same" being ensuring that concurrent jobs are throttled to some maximum. I am assuming that whoever added this intended to track some "too many jobs in the queue" error from the LRM and act according to that. If so, it would be difficult to do this because we do not define a clear mechanism that could allow a clear way for a user to distinguish such an error from other errors. To state that differently, it's not impossible, but it isn't specified. One would have to rely on how the implementation happens to report errors of such type.

- [x] Submit a malformed or unsatisfiable job, then check for the error
  and print it out

Does anybody remember what the intent was here?

- [x] Construct a job that uses all the various "knobs" of the resource
  and job specifications (with some verbose comments thrown in)

I think this is rather generic. Can we be more specific?

**Comment by andre-merzky** [comment]
>     * Submit a malformed or unsatisfiable job, then check for the error
>       and print it out
> 
> 
> Does anybody remember what the intent was here?

Ensure that the `FAILED` state is reached, and show how job is inspected for return code and stderr.

**Comment by SteVwonder** [comment]
> Submit a malformed or unsatisfiable job, then check for the error
and print it out

> Construct a job that uses all the various "knobs" of the resource
and job specifications (with some verbose comments thrown in)

These were covered in #52.  Clicking them as done in the issue body.

I attempted to cover the third one in #114.
